version: "2"

services:
  uc-addon-procon-web-es:
    image: wmucdev.azurecr.io/procon-web-es:6.4.5.0
    container_name: uc-addon-procon-web-es
    restart: on-failure
    cpu_quota: 25000
    volumes:
      - procon-web-projects:/root
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "5"