version: "2"

services:
  uc-addon-procon-web-es:
    image: wmucdev.azurecr.io/uc-addon-procon-web-es:dev
    container_name: uc_addon_procon_web_es
    restart: unless-stopped
    cpu_quota: 25000
    volumes:
      - uc_addon_procon_web_es:/root
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "5"